// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_backend.cpp"
#include "UVLADIE3JM/moc_databasemanager.cpp"
#include "UVLADIE3JM/moc_httpclient.cpp"
#include "UVLADIE3JM/moc_medicaldataprocessor.cpp"
