name: Simple Build (Win7 Compatible)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win7-compatible:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt 5.15.2
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        dir: '${{ github.workspace }}/qt'
        install-deps: 'true'
        modules: 'qtquickcontrols2'
        cache: false

    - name: Download MinGW
      shell: powershell
      run: |
        Write-Host "Downloading MinGW..."
        $mingwUrl = "https://github.com/brechtsanders/winlibs_mingw/releases/download/8.1.0-11.0.0-9.0.0-r6/winlibs-x86_64-posix-seh-gcc-8.1.0-mingw-w64-6.0.0-r6.7z"
        Invoke-WebRequest -Uri $mingwUrl -OutFile "mingw.7z"
        7z x mingw.7z -o"${{ github.workspace }}/mingw"
        Write-Host "MinGW extracted successfully"

    - name: Build with CMake
      shell: cmd
      run: |
        set PATH=${{ github.workspace }}\mingw\mingw64\bin;%PATH%
        set Qt5_DIR=${{ github.workspace }}\qt\Qt\5.15.2\mingw81_64
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%Qt5_DIR%
        mingw32-make -j2

    - name: Deploy application
      shell: cmd
      run: |
        mkdir release
        copy build\QtQmlDemo.exe release\
        cd release
        ${{ github.workspace }}\qt\Qt\5.15.2\mingw81_64\bin\windeployqt.exe --qmldir ..\qml --quick --no-translations --no-system-d3d-compiler --no-opengl-sw --no-angle --no-webkit2 --no-virtualkeyboard --release QtQmlDemo.exe

    - name: Add Win7 compatibility files
      shell: powershell
      run: |
        # Create a batch file for easy launching
        @"
        @echo off
        echo Starting QtQmlDemo...
        set QT_OPENGL=software
        set QT_ANGLE_PLATFORM=d3d9
        start QtQmlDemo.exe
        "@ | Out-File -FilePath "release\Launch_QtQmlDemo.bat" -Encoding ASCII

        # Create README for Windows 7 users
        @"
        QtQmlDemo for Windows 7
        ========================

        Requirements:
        - Windows 7 SP1 or later
        - DirectX 9.0c or later

        To run the application:
        1. Double-click Launch_QtQmlDemo.bat

        If the application doesn't start:
        1. Install Visual C++ Redistributable 2015-2019
        2. Update DirectX
        3. Try running as administrator
        "@ | Out-File -FilePath "release\README_WIN7.txt" -Encoding ASCII

    - name: Create archive
      shell: powershell
      run: |
        Compress-Archive -Path release\* -DestinationPath QtQmlDemo-Win7-Compatible.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: QtQmlDemo-Win7-Compatible
        path: |
          QtQmlDemo-Win7-Compatible.zip
          release/

    - name: Upload executable only
      uses: actions/upload-artifact@v4
      with:
        name: QtQmlDemo-Executable
        path: release/QtQmlDemo.exe