name: Build Win7 Compatible App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Qt
      shell: cmd
      run: |
        pip install aqtinstall

        echo Listing available Qt versions...
        aqt list-qt windows desktop --arch 5.15

        echo Installing Qt 5.15.2...
        aqt install-qt windows desktop 5.15.2 win64_mingw81 -m qtquickcontrols2 -O qt

        echo Installing MinGW...
        aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810 -O qt

        echo Qt installation completed
        dir qt

    - name: Build
      shell: cmd
      run: |
        echo Setting up environment...
        set PATH=%CD%\qt\Tools\mingw810_64\bin;%PATH%
        set Qt5_DIR=%CD%\qt\5.15.2\mingw81_64
        set CMAKE_PREFIX_PATH=%CD%\qt\5.15.2\mingw81_64

        echo Checking Qt installation...
        if exist %Qt5_DIR%\lib\cmake\Qt5\Qt5Config.cmake (
          echo Qt5Config.cmake found
        ) else (
          echo ERROR: Qt5Config.cmake not found
          dir %Qt5_DIR%\lib\cmake
          exit 1
        )

        echo Building project...
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        mingw32-make -j2

        echo Build completed
        dir *.exe

    - name: Package
      shell: cmd
      run: |
        echo Creating deployment package...
        mkdir deploy
        copy build\QtQmlDemo.exe deploy\

        echo Deploying Qt libraries...
        qt\5.15.2\mingw81_64\bin\windeployqt.exe ^
          --dir deploy ^
          --qmldir qml ^
          --quick ^
          --no-translations ^
          --no-system-d3d-compiler ^
          --no-opengl-sw ^
          --release ^
          deploy\QtQmlDemo.exe

        echo Copying MinGW runtime...
        copy qt\Tools\mingw810_64\bin\libgcc_s_seh-1.dll deploy\
        copy qt\Tools\mingw810_64\bin\libstdc++-6.dll deploy\
        copy qt\Tools\mingw810_64\bin\libwinpthread-1.dll deploy\

        echo Creating launcher...
        echo @echo off > deploy\QtQmlDemo.bat
        echo set QT_OPENGL=software >> deploy\QtQmlDemo.bat
        echo start QtQmlDemo.exe %%* >> deploy\QtQmlDemo.bat

        echo Package created
        dir deploy

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: QtQmlDemo-Win7
        path: deploy/
        retention-days: 7